# AUTOGENERATED FROM 'src/queries/users/create_user.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateUserResult(NoPydanticValidation):
    id: uuid.UUID
    first_name: str
    last_name: str
    email: str
    phone: str
    country: str
    created_at: datetime.datetime


async def create_user(
    executor: gel.AsyncIOExecutor,
    *,
    first_name: str,
    last_name: str,
    email: str,
    phone: str,
    country: str,
) -> CreateUserResult:
    return await executor.query_single(
        """\
        select (
            insert accessControl::User {
                first_name := <str>$first_name,
                last_name := <str>$last_name,
                email := <str>$email,
                phone := <str>$phone,
                country := <str>$country
            }
        ) {
            first_name,
            last_name,
            email,
            phone,
            country,
            created_at
        };\
        """,
        first_name=first_name,
        last_name=last_name,
        email=email,
        phone=phone,
        country=country,
    )
