# AUTOGENERATED FROM 'src/queries/users/get_current_user_id.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetCurrentUserIdResult(NoPydanticValidation):
    id: uuid.UUID


async def get_current_user_id(
    executor: gel.AsyncIOExecutor,
) -> GetCurrentUserIdResult | None:
    return await executor.query_single(
        """\
        select accessControl::User {
          id
        }
        filter .identity = global ext::auth::ClientTokenIdentity\
        """,
    )
