# AUTOGENERATED FROM 'src/queries/memory/create_user_profile.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateUserProfileResult(NoPydanticValidation):
    id: uuid.UUID


async def create_user_profile(
    executor: gel.AsyncIOExecutor,
    *,
    userid: uuid.UUID,
    country: str,
    kyc_passed: bool,
) -> CreateUserProfileResult:
    return await executor.query_single(
        """\
        INSERT userProfile::Profile {
            user := (SELECT accessControl::User FILTER .id = <uuid>$userid),
            country := <str>$country,
            kyc_passed := <bool>$kyc_passed
        };\
        """,
        userid=userid,
        country=country,
        kyc_passed=kyc_passed,
    )
