# AUTOGENERATED FROM 'src/queries/memory/get_user_investment_preferences.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import enum
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserInvestmentPreferencesResult(NoPydanticValidation):
    id: uuid.UUID
    investment_horizon: UserprofileInvestmentHorizon | None
    age_group: UserprofileAgeGroup | None
    risk_appetite: int | None
    reason_for_investing: str | None
    other_investments: list[str]
    investment_knowledge: UserprofileInvestmentKnowledge | None
    financial_goals: list[str]


class UserprofileAgeGroup(enum.Enum):
    UNDER25 = "under25"
    E_25_34 = "25-34"
    E_35_44 = "35-44"
    E_45_54 = "45-54"
    E_55PLUS = "55plus"


class UserprofileInvestmentHorizon(enum.Enum):
    E_1_5 = "1-5"
    E_6_10 = "6-10"
    E_10_20 = "10-20"
    E_20PLUS = "20plus"


class UserprofileInvestmentKnowledge(enum.Enum):
    NOVICE = "novice"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


async def get_user_investment_preferences(
    executor: gel.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> GetUserInvestmentPreferencesResult | None:
    return await executor.query_single(
        """\
        select userProfile::Profile {
            investment_horizon,
            age_group,
            risk_appetite,
            reason_for_investing,
            other_investments,
            investment_knowledge,
            financial_goals
        }
        filter .user.id = <uuid>$user_id
        limit 1\
        """,
        user_id=user_id,
    )
