# AUTOGENERATED FROM 'src/queries/memory/get_user_investment_preferences.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import enum
import gel
import uuid


UserprofileRiskAppetite = int


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserInvestmentPreferencesResult(NoPydanticValidation):
    id: uuid.UUID
    stated_investment_horizon: UserprofileInvestmentHorizon | None
    inferred_investment_horizon: UserprofileInvestmentHorizon | None
    stated_risk_appetite: UserprofileRiskAppetite | None
    inferred_risk_appetite: UserprofileRiskAppetite | None
    stated_investment_knowledge: UserprofileInvestmentKnowledge | None
    inferred_investment_knowledge: UserprofileInvestmentKnowledge | None
    stated_financial_goals: list[str]
    inferred_financial_goals: list[str]
    other_investments: list[str]
    inferred_investment_thesis: str | None


class UserprofileInvestmentHorizon(enum.Enum):
    E_1_5 = "1-5"
    E_6_10 = "6-10"
    E_10_20 = "10-20"
    E_20PLUS = "20plus"


class UserprofileInvestmentKnowledge(enum.Enum):
    NOVICE = "novice"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


async def get_user_investment_preferences(
    executor: gel.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> GetUserInvestmentPreferencesResult | None:
    return await executor.query_single(
        """\
        select userProfile::Profile {
            stated_investment_horizon,
            inferred_investment_horizon,
            stated_risk_appetite,
            inferred_risk_appetite,
            stated_investment_knowledge,
            inferred_investment_knowledge,
            stated_financial_goals,
            inferred_financial_goals,
            other_investments,
            inferred_investment_thesis
        }
        filter .user.id = <uuid>$user_id
        limit 1\
        """,
        user_id=user_id,
    )
