# AUTOGENERATED FROM 'src/queries/memory/update_user_profile.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import enum
import gel
import uuid


UserprofileRiskAppetite = int


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateUserProfileResult(NoPydanticValidation):
    id: uuid.UUID


class UserprofileAgeGroup(enum.Enum):
    UNDER25 = "under25"
    E_25_34 = "25-34"
    E_35_44 = "35-44"
    E_45_54 = "45-54"
    E_55PLUS = "55plus"


class UserprofileInvestmentHorizon(enum.Enum):
    E_1_5 = "1-5"
    E_6_10 = "6-10"
    E_10_20 = "10-20"
    E_20PLUS = "20plus"


class UserprofileInvestmentKnowledge(enum.Enum):
    NOVICE = "novice"
    INTERMEDIATE = "intermediate"
    ADVANCED = "advanced"


async def update_user_profile(
    executor: gel.AsyncIOExecutor,
    *,
    country: str,
    kyc_passed: bool,
    age_group: UserprofileAgeGroup,
    stated_investment_horizon: UserprofileInvestmentHorizon,
    stated_risk_appetite: UserprofileRiskAppetite,
    stated_investment_knowledge: UserprofileInvestmentKnowledge,
    stated_financial_goals: list[str],
    other_investments: list[str],
    inferred_investment_horizon: UserprofileInvestmentHorizon,
    inferred_risk_appetite: UserprofileRiskAppetite,
    inferred_investment_knowledge: UserprofileInvestmentKnowledge,
    inferred_financial_goals: list[str],
    inferred_investment_thesis: str,
    userid: uuid.UUID,
) -> list[UpdateUserProfileResult]:
    return await executor.query(
        """\
        UPDATE userProfile::Profile
        FILTER .user.id = <uuid>$userid
        SET {
            country := <str>$country,
            kyc_passed := <bool>$kyc_passed,
            age_group := <userProfile::AgeGroup>$age_group,
            stated_investment_horizon := <userProfile::InvestmentHorizon>$stated_investment_horizon,
            stated_risk_appetite := <userProfile::RiskAppetite>$stated_risk_appetite,
            stated_investment_knowledge := <userProfile::InvestmentKnowledge>$stated_investment_knowledge,
            stated_financial_goals := array_unpack(<array<str>>$stated_financial_goals),
            other_investments := array_unpack(<array<str>>$other_investments),
            inferred_investment_horizon := <userProfile::InvestmentHorizon>$inferred_investment_horizon,
            inferred_risk_appetite := <userProfile::RiskAppetite>$inferred_risk_appetite,
            inferred_investment_knowledge := <userProfile::InvestmentKnowledge>$inferred_investment_knowledge,
            inferred_financial_goals := array_unpack(<array<str>>$inferred_financial_goals),
            inferred_investment_thesis := <str>$inferred_investment_thesis,
        };\
        """,
        country=country,
        kyc_passed=kyc_passed,
        age_group=age_group,
        stated_investment_horizon=stated_investment_horizon,
        stated_risk_appetite=stated_risk_appetite,
        stated_investment_knowledge=stated_investment_knowledge,
        stated_financial_goals=stated_financial_goals,
        other_investments=other_investments,
        inferred_investment_horizon=inferred_investment_horizon,
        inferred_risk_appetite=inferred_risk_appetite,
        inferred_investment_knowledge=inferred_investment_knowledge,
        inferred_financial_goals=inferred_financial_goals,
        inferred_investment_thesis=inferred_investment_thesis,
        userid=userid,
    )
