# AUTOGENERATED FROM 'src/queries/messaging/archive_messages.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class ArchiveMessagesResult(NoPydanticValidation):
    id: uuid.UUID


async def archive_messages(
    executor: gel.AsyncIOExecutor,
    *,
    chat_id: uuid.UUID,
) -> list[ArchiveMessagesResult]:
    return await executor.query(
        """\
        with 
            cutoff_message := (
                select messaging::Message
                filter .chat.id = <uuid>$chat_id and not .is_archived
                order by .created_at desc
                offset 29 limit 1  # 30th most recent message
            )
        update messaging::Message
        filter (
            .chat.id = <uuid>$chat_id and
            not .is_archived and
            .created_at < cutoff_message.created_at
        )
        set {
            is_archived := true
        };\
        """,
        chat_id=chat_id,
    )
