# AUTOGENERATED FROM 'src/queries/messaging/create_message.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateMessageResult(NoPydanticValidation):
    id: uuid.UUID


async def create_message(
    executor: gel.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
    chat_id: uuid.UUID,
    role: str,
    channel: str,
    content: str,
) -> CreateMessageResult:
    return await executor.query_single(
        """\
        with
            user := (select accessControl::User filter .id = <uuid>$user_id),
            chat := (select assert_exists(user.<owner[is messaging::Chat] filter .id = <uuid>$chat_id))
        insert messaging::Message {
            chat := chat,
            role := <str>$role,
            channel := <str>$channel,
            content := <str>$content,
            created_at := datetime_current(),
            is_archived := false,
        }\
        """,
        user_id=user_id,
        chat_id=chat_id,
        role=role,
        channel=channel,
        content=content,
    )
