# AUTOGENERATED FROM 'src/queries/messaging/create_summary_and_archive.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateSummaryAndArchiveResult(NoPydanticValidation):
    summary: CreateSummaryAndArchiveResultSummary
    archived_messages: list[CreateSummaryAndArchiveResultArchivedMessagesItem]


@dataclasses.dataclass
class CreateSummaryAndArchiveResultArchivedMessagesItem(NoPydanticValidation):
    id: uuid.UUID


@dataclasses.dataclass
class CreateSummaryAndArchiveResultSummary(NoPydanticValidation):
    id: uuid.UUID


async def create_summary_and_archive(
    executor: gel.AsyncIOExecutor,
    *,
    chat_id: uuid.UUID,
    content: str,
    range_start: datetime.datetime,
    range_end: datetime.datetime,
    message_ids: list[uuid.UUID],
) -> CreateSummaryAndArchiveResult:
    return await executor.query_single(
        """\
        with
          chat_id := <uuid>$chat_id,
          summary_content := <str>$content,
          range_start := <datetime>$range_start,
          range_end := <datetime>$range_end,
          message_ids := <array<uuid>>$message_ids

        select {
          summary := (
            insert messaging::Summary {
              chat := (select messaging::Chat filter .id = chat_id),
              content := summary_content,
              range_start := range_start,
              range_end := range_end
            }
          ),
          archived_messages := (
            update messaging::Message
            filter .id in array_unpack(message_ids)
            set {
              status := messaging::MessageStatus.Archived
            }
          )
        }\
        """,
        chat_id=chat_id,
        content=content,
        range_start=range_start,
        range_end=range_end,
        message_ids=message_ids,
    )
