# AUTOGENERATED FROM 'src/queries/messaging/create_chat.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateChatResult(NoPydanticValidation):
    id: uuid.UUID
    created_at: datetime.datetime
    owner: CreateChatResultOwner


@dataclasses.dataclass
class CreateChatResultOwner(NoPydanticValidation):
    id: uuid.UUID
    email: str


async def create_chat(
    executor: gel.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> CreateChatResult:
    return await executor.query_single(
        """\
        select (
            insert messaging::Chat {
                owner := (select accessControl::User filter .id = <uuid>$user_id)
            }
        ) {
            id,
            created_at,
            owner: {
                id,
                email
            }
        };\
        """,
        user_id=user_id,
    )
