# AUTOGENERATED FROM 'src/queries/messaging/create_message.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class CreateMessageResult(NoPydanticValidation):
    id: uuid.UUID
    role: str
    content: str
    created_at: datetime.datetime | None
    chat: CreateMessageResultChat


@dataclasses.dataclass
class CreateMessageResultChat(NoPydanticValidation):
    id: uuid.UUID


async def create_message(
    executor: gel.AsyncIOExecutor,
    *,
    role: str,
    content: str,
    chat_id: uuid.UUID,
) -> CreateMessageResult:
    return await executor.query_single(
        """\
        select (
            insert messaging::Message {
                role := <str>$role,
                content := <str>$content,
                chat := (select messaging::Chat filter .id = <uuid>$chat_id)
            }
        ) {
            id,
            role,
            content,
            created_at,
            chat: {
                id
            }
        };\
        """,
        role=role,
        content=content,
        chat_id=chat_id,
    )
