# AUTOGENERATED FROM 'src/queries/messaging/get_user_recent_messages.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserRecentMessagesResult(NoPydanticValidation):
    id: uuid.UUID
    created_at: datetime.datetime
    message_count: int
    recent_message_count: int
    recent_messages: list[GetUserRecentMessagesResultRecentMessagesItem]


@dataclasses.dataclass
class GetUserRecentMessagesResultRecentMessagesItem(NoPydanticValidation):
    id: uuid.UUID
    content: str
    role: str
    created_at: datetime.datetime | None


async def get_user_recent_messages(
    executor: gel.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
) -> list[GetUserRecentMessagesResult]:
    return await executor.query(
        """\
        with user := (select accessControl::User filter .id = <uuid>$user_id)
        select user.<owner[is messaging::Chat] {
            id,
            created_at,
            message_count := count(.archive),
            recent_message_count := count(.recent_messages),
            recent_messages := (
                select .recent_messages {
                    content,
                    role,
                    created_at
                }
                order by .created_at desc
            )
        }
        order by .created_at desc;\
        """,
        user_id=user_id,
    )
