# AUTOGENERATED FROM 'src/queries/messaging/get_user_by_phone.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetUserByPhoneResult(NoPydanticValidation):
    id: uuid.UUID
    first_name: str
    last_name: str
    phone: str


async def get_user_by_phone(
    executor: gel.AsyncIOExecutor,
    *,
    phone_number: str,
) -> GetUserByPhoneResult | None:
    return await executor.query_single(
        """\
        select accessControl::User {id, first_name, last_name, phone}
        filter accessControl::User.phone = <str>$phone_number\
        """,
        phone_number=phone_number,
    )
