# AUTOGENERATED FROM 'src/queries/messaging/get_chat.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetChatResult(NoPydanticValidation):
    id: uuid.UUID


async def get_chat(
    executor: gel.AsyncIOExecutor,
    *,
    user_id: uuid.UUID,
    chat_id: uuid.UUID,
) -> GetChatResult:
    return await executor.query_single(
        """\
        with
            user := (select accessControl::User filter .id = <uuid>$user_id),
            chat := (select user.<owner[is messaging::Chat] filter .id = <uuid>$chat_id)
        select assert_exists(chat) {
            id,
            # We'll add message retrieval later
        }\
        """,
        user_id=user_id,
        chat_id=chat_id,
    )
