# AUTOGENERATED FROM 'src/queries/messaging/get_messages_to_summarize.edgeql' WITH:
#     $ gel-py


from __future__ import annotations
import dataclasses
import datetime
import gel
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_pydantic_core_schema__(cls, _source_type, _handler):
        # Pydantic 2.x
        from pydantic_core.core_schema import any_schema
        return any_schema()

    @classmethod
    def __get_validators__(cls):
        # Pydantic 1.x
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        _ = pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class GetMessagesToSummarizeResult(NoPydanticValidation):
    id: uuid.UUID
    role: str
    content: str
    created_at: datetime.datetime | None


async def get_messages_to_summarize(
    executor: gel.AsyncIOExecutor,
    *,
    chat_id: uuid.UUID,
) -> list[GetMessagesToSummarizeResult]:
    return await executor.query(
        """\
        select messaging::Message {
          id,
          role,
          content,
          created_at
        }
        filter
          .chat.id = <uuid>$chat_id
          and .status = messaging::MessageStatus.PendingSummary
        order by .created_at asc
        limit 20\
        """,
        chat_id=chat_id,
    )
